# Generated by Django 4.0.4 on 2022-12-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_file', models.ImageField(upload_to='insurance_files/')),
            ],
        ),
    ]
